package dev.cfmobile.app.ui.navigation

import java.net.URLDecoder
import java.net.URLEncoder

object Routes {
    const val LOGIN = "login"
    const val DASHBOARD = "dashboard"
    const val ZONES = "zones"
    const val SETTINGS = "settings"
    const val SECURITY = "security"
    const val ZONE_MENU = "zone/{zoneId}/{zoneName}"
    const val ACCOUNT_MEMBERS = "account/{accountId}/members"
    const val AUDIT_LOGS = "account/{accountId}/auditlogs"
    const val LOAD_BALANCING = "account/{accountId}/loadbalancing"
    const val R2 = "account/{accountId}/r2"
    const val KV = "account/{accountId}/kv"
    const val KV_KEYS = "account/{accountId}/kv/{namespaceId}/{namespaceTitle}"
    const val D1 = "account/{accountId}/d1"
    const val D1_CONSOLE = "account/{accountId}/d1/{databaseId}/{databaseName}/query"
    const val WORKERS = "account/{accountId}/workers"
    const val PAGES = "account/{accountId}/pages"
    const val ACCESS = "account/{accountId}/access"
    const val GATEWAY = "account/{accountId}/gateway"
    const val GATEWAY_LISTS = "account/{accountId}/gatewaylists"
    const val ACCESS_IDENTITY = "account/{accountId}/accessidentity"
    const val TUNNELS = "account/{accountId}/tunnels"
    const val QUEUES = "account/{accountId}/queues"
    const val DURABLE_OBJECTS = "account/{accountId}/durableobjects"
    const val WORKFLOWS = "account/{accountId}/workflows"
    const val HYPERDRIVE = "account/{accountId}/hyperdrive"
    const val VECTORIZE = "account/{accountId}/vectorize"
    const val STREAM = "account/{accountId}/stream"
    const val IMAGES = "account/{accountId}/images"
    const val TURNSTILE = "account/{accountId}/turnstile"
    const val LOGPUSH = "account/{accountId}/logpush"
    const val WORKERS_AI = "account/{accountId}/workersai"
    const val DEVICE_POSTURE = "account/{accountId}/deviceposture"
    const val MAGIC_NETWORK = "account/{accountId}/magicnetwork"
    const val BILLING = "account/{accountId}/billing"
    const val API_TOKENS = "account/{accountId}/apitokens"
    const val NOTIFICATIONS = "account/{accountId}/notifications"
    const val BULK_REDIRECTS = "account/{accountId}/bulkredirects"
    const val REGISTRAR = "account/{accountId}/registrar"
    const val WEB_ANALYTICS = "account/{accountId}/webanalytics"
    const val BROWSER_RENDERING = "account/{accountId}/browserrendering"
    const val DNS = "zone/{zoneId}/{zoneName}/dns"
    const val SSL = "zone/{zoneId}/{zoneName}/ssl"
    const val FIREWALL = "zone/{zoneId}/{zoneName}/firewall"
    const val WAF = "zone/{zoneId}/{zoneName}/waf"
    const val RATE_LIMITING = "zone/{zoneId}/{zoneName}/ratelimit"
    const val TRANSFORM_RULES = "zone/{zoneId}/{zoneName}/transformrules"
    const val REDIRECT_RULES = "zone/{zoneId}/{zoneName}/redirectrules"
    const val ORIGIN_RULES = "zone/{zoneId}/{zoneName}/originrules"
    const val CACHE_RULES = "zone/{zoneId}/{zoneName}/cacherules"
    const val MANAGED_WAF = "zone/{zoneId}/{zoneName}/managedwaf"
    const val PAGE_RULES = "zone/{zoneId}/{zoneName}/pagerules"
    const val CACHING = "zone/{zoneId}/{zoneName}/caching"
    const val SECURITY_EVENTS = "zone/{zoneId}/{zoneName}/securityevents"
    const val PAGE_SHIELD = "zone/{zoneId}/{zoneName}/pageshield"
    const val DDOS = "zone/{zoneId}/{zoneName}/ddos"
    const val API_SHIELD = "zone/{zoneId}/{zoneName}/apishield"
    const val EMAIL_ROUTING = "zone/{zoneId}/{zoneName}/emailrouting"
    const val SPECTRUM = "zone/{zoneId}/{zoneName}/spectrum"
    const val SPEED = "zone/{zoneId}/{zoneName}/speed"
    const val NETWORK = "zone/{zoneId}/{zoneName}/network"
    const val SCRAPE_SHIELD = "zone/{zoneId}/{zoneName}/scrapeshield"
    const val CACHE_BEHAVIOUR = "zone/{zoneId}/{zoneName}/cachebehaviour"
    const val CERTIFICATES = "zone/{zoneId}/{zoneName}/certificates"
    const val WAITING_ROOM = "zone/{zoneId}/{zoneName}/waitingroom"
    const val HEALTH_CHECKS = "zone/{zoneId}/{zoneName}/healthchecks"
    const val WORKER_ROUTES = "zone/{zoneId}/{zoneName}/workerroutes"
    const val ANALYTICS = "zone/{zoneId}/{zoneName}/analytics"
    const val BOT_MANAGEMENT = "zone/{zoneId}/{zoneName}/botmanagement"

    /** Zone names (domains) only ever contain URL-safe characters, but this encodes anyway
     *  rather than assuming - a nav route argument is still a URL path segment. */
    private fun encode(value: String) = URLEncoder.encode(value, "UTF-8")

    fun decodeZoneName(raw: String): String = URLDecoder.decode(raw, "UTF-8")

    /** Same decode, for any other name carried through a route argument. */
    fun decodeArg(raw: String): String = URLDecoder.decode(raw, "UTF-8")

    fun zoneMenu(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}"
    fun accountMembers(accountId: String) = "account/$accountId/members"
    fun auditLogs(accountId: String) = "account/$accountId/auditlogs"
    fun loadBalancing(accountId: String) = "account/$accountId/loadbalancing"
    fun r2(accountId: String) = "account/$accountId/r2"
    fun kv(accountId: String) = "account/$accountId/kv"
    fun kvKeys(accountId: String, namespaceId: String, namespaceTitle: String) =
        "account/$accountId/kv/$namespaceId/${encode(namespaceTitle)}"
    fun d1(accountId: String) = "account/$accountId/d1"
    fun d1Console(accountId: String, databaseId: String, databaseName: String) =
        "account/$accountId/d1/$databaseId/${encode(databaseName)}/query"
    fun workers(accountId: String) = "account/$accountId/workers"
    fun pages(accountId: String) = "account/$accountId/pages"
    fun access(accountId: String) = "account/$accountId/access"
    fun gateway(accountId: String) = "account/$accountId/gateway"
    fun gatewayLists(accountId: String) = "account/$accountId/gatewaylists"
    fun accessIdentity(accountId: String) = "account/$accountId/accessidentity"
    fun tunnels(accountId: String) = "account/$accountId/tunnels"
    fun queues(accountId: String) = "account/$accountId/queues"
    fun durableObjects(accountId: String) = "account/$accountId/durableobjects"
    fun workflows(accountId: String) = "account/$accountId/workflows"
    fun hyperdrive(accountId: String) = "account/$accountId/hyperdrive"
    fun vectorize(accountId: String) = "account/$accountId/vectorize"
    fun stream(accountId: String) = "account/$accountId/stream"
    fun images(accountId: String) = "account/$accountId/images"
    fun turnstile(accountId: String) = "account/$accountId/turnstile"
    fun logpush(accountId: String) = "account/$accountId/logpush"
    fun workersAi(accountId: String) = "account/$accountId/workersai"
    fun devicePosture(accountId: String) = "account/$accountId/deviceposture"
    fun magicNetwork(accountId: String) = "account/$accountId/magicnetwork"
    fun billing(accountId: String) = "account/$accountId/billing"
    fun apiTokens(accountId: String) = "account/$accountId/apitokens"
    fun notifications(accountId: String) = "account/$accountId/notifications"
    fun bulkRedirects(accountId: String) = "account/$accountId/bulkredirects"
    fun registrar(accountId: String) = "account/$accountId/registrar"
    fun webAnalytics(accountId: String) = "account/$accountId/webanalytics"
    fun browserRendering(accountId: String) = "account/$accountId/browserrendering"
    fun dns(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/dns"
    fun ssl(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/ssl"
    fun firewall(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/firewall"
    fun waf(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/waf"
    fun rateLimiting(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/ratelimit"
    fun transformRules(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/transformrules"
    fun redirectRules(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/redirectrules"
    fun originRules(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/originrules"
    fun cacheRules(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/cacherules"
    fun managedWaf(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/managedwaf"
    fun pageRules(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/pagerules"
    fun caching(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/caching"
    fun securityEvents(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/securityevents"
    fun pageShield(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/pageshield"
    fun ddos(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/ddos"
    fun apiShield(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/apishield"
    fun emailRouting(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/emailrouting"
    fun spectrum(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/spectrum"
    fun speed(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/speed"
    fun network(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/network"
    fun scrapeShield(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/scrapeshield"
    fun cacheBehaviour(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/cachebehaviour"
    fun certificates(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/certificates"
    fun waitingRoom(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/waitingroom"
    fun healthChecks(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/healthchecks"
    fun workerRoutes(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/workerroutes"
    fun analytics(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/analytics"
    fun botManagement(zoneId: String, zoneName: String) = "zone/$zoneId/${encode(zoneName)}/botmanagement"
}
