package dev.cfmobile.app.core.capabilities

/**
 * Binds each native screen to one representative read operation in Cloudflare's schema.
 * The permissions a screen needs are then taken from the schema's own metadata for that
 * operation (`x-api-token-group`), not written down here, so they follow Cloudflare's
 * permission catalog as it changes. CapabilityProbesTest fails if a binding stops resolving.
 */
object CapabilityProbes {
    data class Probe(val method: String, val path: String)

    private fun get(path: String) = Probe("GET", path)

    val byCapabilityId: Map<String, Probe> = mapOf(
        "dns.records" to get("zones/{zone_id}/dns_records"),
        "ssl.tls" to get("zones/{zone_id}/settings/{setting_id}"),
        "firewall.legacy" to get("zones/{zone_id}/firewall/access_rules/rules"),
        "legacy_firewall" to get("zones/{zone_id}/firewall/lockdowns"),
        "waf.rulesets" to get("zones/{zone_id}/rulesets"),
        "rate_limiting" to get("zones/{zone_id}/rulesets"),
        "transform_rules" to get("zones/{zone_id}/rulesets"),
        "redirect_rules" to get("zones/{zone_id}/rulesets"),
        "origin_rules" to get("zones/{zone_id}/rulesets"),
        "cache_rules" to get("zones/{zone_id}/rulesets"),
        "managed_waf" to get("zones/{zone_id}/rulesets"),
        "config_rules" to get("zones/{zone_id}/rulesets"),
        "page_rules" to get("zones/{zone_id}/pagerules"),
        "caching" to get("zones/{zone_id}/settings/{setting_id}"),
        "certificates" to get("zones/{zone_id}/ssl/certificate_packs"),
        "client_certificates" to get("zones/{zone_id}/client_certificates"),
        "zone_ownership" to get("zones/{zone_id}/hold"),
        "waiting_room" to get("zones/{zone_id}/waiting_rooms"),
        "health_checks" to get("zones/{zone_id}/healthchecks"),
        "speed" to get("zones/{zone_id}/settings"),
        "network_settings" to get("zones/{zone_id}/settings"),
        "scrape_shield" to get("zones/{zone_id}/settings"),
        "performance" to get("zones/{zone_id}/argo/smart_routing"),
        "cache_behaviour" to get("zones/{zone_id}/settings"),
        "snippets" to get("zones/{zone_id}/snippets"),
        "cloud_connector" to get("zones/{zone_id}/cloud_connector/rules"),
        "custom_pages" to get("zones/{zone_id}/custom_pages"),
        "zaraz" to get("zones/{zone_id}/settings/zaraz/config"),
        "analytics" to get("zones/{zone_id}/settings"),
        "security_events" to get("zones/{zone_id}/settings"),
        "audit_logs" to get("accounts/{account_id}/audit_logs"),
        "load_balancing" to get("accounts/{account_id}/load_balancers/pools"),
        "page_shield" to get("zones/{zone_id}/page_shield"),
        "api_shield" to get("zones/{zone_id}/api_gateway/operations"),
        "bot_management" to get("zones/{zone_id}/bot_management"),
        "ddos" to get("zones/{zone_id}/rulesets"),
        "workers" to get("accounts/{account_id}/workers/scripts"),
        "worker_routes" to get("zones/{zone_id}/workers/routes"),
        "worker_domains" to get("accounts/{account_id}/workers/domains"),
        "pages" to get("accounts/{account_id}/pages/projects"),
        "r2" to get("accounts/{account_id}/r2/buckets"),
        "kv" to get("accounts/{account_id}/storage/kv/namespaces"),
        "d1" to get("accounts/{account_id}/d1/database"),
        "queues" to get("accounts/{account_id}/queues"),
        "access" to get("accounts/{account_id}/access/apps"),
        "access_identity" to get("accounts/{account_id}/access/identity_providers"),
        "gateway" to get("accounts/{account_id}/gateway/rules"),
        "access_directory" to get("accounts/{account_id}/access/groups"),
        "zero_trust_network" to get("accounts/{account_id}/teamnet/routes"),
        "gateway_lists" to get("accounts/{account_id}/gateway/lists"),
        "tunnels" to get("accounts/{account_id}/cfd_tunnel"),
        "device_posture" to get("accounts/{account_id}/devices/posture"),
        "account_members" to get("accounts/{account_id}/members"),
        "durable_objects" to get("accounts/{account_id}/workers/durable_objects/namespaces"),
        "workflows" to get("accounts/{account_id}/workflows"),
        "hyperdrive" to get("accounts/{account_id}/hyperdrive/configs"),
        "ai" to get("accounts/{account_id}/ai/models/search"),
        "vectorize" to get("accounts/{account_id}/vectorize/v2/indexes"),
        "stream" to get("accounts/{account_id}/stream"),
        "images" to get("accounts/{account_id}/images/v1"),
        "email_routing" to get("zones/{zone_id}/email/routing/rules"),
        "turnstile" to get("accounts/{account_id}/challenges/widgets"),
        "spectrum" to get("zones/{zone_id}/spectrum/apps"),
        "magic_network" to get("accounts/{account_id}/magic/sites"),
        "magic_firewall" to get("accounts/{account_id}/rulesets"),
        "addressing" to get("accounts/{account_id}/addressing/prefixes"),
        "request_tracer" to Probe("POST", "accounts/{account_id}/request-tracer/trace"),
        "web3" to get("zones/{zone_id}/web3/hostnames"),
        "dns_settings" to get("zones/{zone_id}/dns_settings"),
        "logpush" to get("accounts/{account_id}/logpush/jobs"),
        "api_tokens" to get("user/tokens"),
        "notifications" to get("accounts/{account_id}/alerting/v3/policies"),
        "platform" to get("accounts/{account_id}/secrets_store/stores"),
        "dns_firewall" to get("accounts/{account_id}/dns_firewall"),
        "bulk_redirects" to get("accounts/{account_id}/rules/lists"),
        "registrar" to get("accounts/{account_id}/registrar/domains"),
        "web_analytics" to get("accounts/{account_id}/rum/site_info/list"),
        "billing" to get("accounts/{account_id}/subscriptions"),
        "browser_rendering" to Probe("POST", "accounts/{account_id}/browser-rendering/screenshot")
    )
}
